title: bigreddmachine.github.io
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
    - github-pages
xmr: 42CnLwEuuhrHkn6tmVHD8T4qHfji988ciLxGv9PsauDcABYYxNTHtf9UhAkr79z2G7M5r93YbimeJ6m6hkwn2AX27snNG5q
